trigger:
- master

jobs:
- job: BuildMacOSWithSonarQube
  displayName: Build for MacOS With SonarQube
  dependsOn: []
  pool:
    vmImage: 'macOS-latest'
  steps:
  - task: SonarQubePrepare@4
    inputs:
      SonarQube: 'Peach'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'geoffray-azure-cmake-macosx-test'
      cliProjectName: 'geoffray-azure-cmake-macosx-test'
      cliSources: 'src'
      extraProperties: 'sonar.cfamily.build-wrapper-output=build_wrapper_output_directory'
  - bash: |
      curl 'https://peach.sonarsource.com/static/cpp/build-wrapper-macosx-x86.zip' --output build-wrapper-macosx-x86.zip
      unzip build-wrapper-macosx-x86.zip
    displayName: Install buildwrapper
  - bash: |
      mkdir build
      cd build
      cmake ..
    workingDirectory: .
    displayName: Prepare build
  - bash: |
      build-wrapper-macosx-x86/build-wrapper-macosx-x86  --out-dir build_wrapper_output_directory cmake --build build/ --config Release
    displayName: Compile project in build wrapper
  - task: SonarQubeAnalyze@4

- job: BuildMacOSWithSonarCloud
  displayName: Build for MacOS With SonarCloud
  dependsOn: []
  pool:
    vmImage: 'macOS-latest'
  steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud'
      organization: 'geoffray-adde-sonarsource-github'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'geoffray-azure-cmake-macosx-test'
      cliProjectName: 'geoffray-azure-cmake-macosx-test'
      cliSources: 'src'
      extraProperties: 'sonar.cfamily.build-wrapper-output=build_wrapper_output_directory'
  - bash: |
      curl 'https://peach.sonarsource.com/static/cpp/build-wrapper-macosx-x86.zip' --output build-wrapper-macosx-x86.zip
      unzip build-wrapper-macosx-x86.zip
    displayName: Install buildwrapper
  - bash: |
      mkdir build
      cd build
      cmake ..
    workingDirectory: .
    displayName: Prepare build
  - bash: |
      build-wrapper-macosx-x86/build-wrapper-macosx-x86  --out-dir build_wrapper_output_directory cmake --build build/ --config Release
    displayName: Compile project in build wrapper
  - task: SonarCloudAnalyze@1